name: project-automation
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add new issues to the core/app project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458 #v1.0.1
        with:
          project-url: https://github.com/orgs/celestiaorg/projects/24
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
